### ISSUE TITLE
Error in current build

### ISSUE THREAD

**Issue by Togglebutton** [NekoNova/Communictor#3]
type 'function' is not supported by JSON.
stack trace:
    [C]: in function 'error'
    ...g\NCSOFT\WildStar\Addons\Communictor\LibJSON-2.5.lua:358: in function <...g\NCSOFT\WildStar\Addons\Communictor\LibJSON-2.5.lua:349>
    (tail call): ?
    ...\NCSOFT\WildStar\Addons\Communictor\communicator.lua:824: in function <...\NCSOFT\WildStar\Addons\Communictor\communicator.lua:814>

type 'function' is not supported by JSON.
stack trace:
    [C]: in function 'error'
    ...g\NCSOFT\WildStar\Addons\Communictor\LibJSON-2.5.lua:358: in function <...g\NCSOFT\WildStar\Addons\Communictor\LibJSON-2.5.lua:349>
    (tail call): ?
    ...\NCSOFT\WildStar\Addons\Communictor\communicator.lua:824: in function <...\NCSOFT\WildStar\Addons\Communictor\communicator.lua:814>

**Comment by coding-red-panda** [comment]
it's trying to serialise a function.
Then my question is, how did a function callback get stored in a Message property.

**Comment by Togglebutton** [comment]
Going to need some debug tracing to figure out what it's trying to pass.

**Comment by Togglebutton** [comment]
Appears the be GetPayload() method.

**Comment by Togglebutton** [comment]
Found the problem. Payload on Version Query was not being set. Will post to repo.

**Comment by Togglebutton** [comment]
Oh, dope, wrong. It's the non existent Pop() method being called. In fact, the Object that the queue is prototyped with doesn't exist.

**Comment by Togglebutton** [comment]
Fixed in latest commit. Was actually calling LibJSON method wrong (was calling as method instead of function)
